---
- name: Create DDNS-Updater Directories
  file:
    path: "{{ item }}"
    state: directory
    group: "1000"
    mode: 0775
  with_items:
    - "{{ ddns_updater_data_directory }}"
    - "{{ ddns_updater_data_directory }}/data"

- name: Create DDNS-Updater Docker Container
  docker_container:
    name: ddns-updater
    image: qmcgaw/ddns-updater:latest
    pull: true
    volumes:
      - "{{ ddns_updater_data_directory }}/data:/updater/data:rw"
    ports:
      - "{{ ddns_updater_port }}:{{ ddns_updater_port }}"
    env:
      LISTENING_PORT: "{{ ddns_updater_port }}"
      BACKUP_PERIOD: "24h"
      TZ: "{{ ansible_nas_timezone }}"
    restart_policy: unless-stopped
    memory: "{{ ddns_updater_memory }}"
    labels:
      traefik.enable: "{{ ddns_updater_available_externally | string }}"
      traefik.http.routers.ddns_updater.rule: "Host(`{{ ddns_updater_hostname }}.{{ ansible_nas_domain }}`)"
      traefik.http.routers.ddns_updater.tls.certresolver: "letsencrypt"
      traefik.http.routers.ddns_updater.tls.domains[0].main: "{{ ansible_nas_domain }}"
      traefik.http.routers.ddns_updater.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
      traefik.http.services.ddns_updater.loadbalancer.server.port: "{{ ddns_updater_port }}"
