---
- name: Create Handbrake Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ handbrake_data_directory }}"
    - "{{ handbrake_data_directory }}/config"
    - "{{ handbrake_output_directory }}"
    - "{{ handbrake_watch_directory }}"
- name: Create HandBrake Docker Container
  docker_container:
    name: handbrake
    image: jlesage/handbrake
    pull: true
    volumes:
      - "{{ handbrake_data_directory }}:/config:rw"
      - "{{ handbrake_storage_directory }}:/storage:ro"
      - "{{ handbrake_watch_directory }}:/watch:rw"
      - "{{ handbrake_output_directory }}:/output:rw"
    ports:
      - "{{ handbrake_port_http }}:5800"
    dns_servers: "{{ ansible_nas_dns }}"
    hostname: "handbrake"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      USER_ID: "{{ handbrake_user_id }}"
      GROUP_ID: "{{ handbrake_group_id }}"
      KEEP_APP_RUNNING: "{{ handbrake_KEEP_APP_RUNNING }}"
      AUTOMATED_CONVERSION_PRESET: "{{ handbrake_AUTOMATED_CONVERSION_PRESET }}"
      AUTOMATED_CONVERSION_FORMAT: "{{ handbrake_AUTOMATED_CONVERSION_FORMAT }}"
      AUTOMATED_CONVERSION_KEEP_SOURCE: "{{ handbrake_AUTOMATED_CONVERSION_KEEP_SOURCE }}"
      AUTOMATED_CONVERSION_NON_VIDEO_FILE_ACTION: "{{ handbrake_AUTOMATED_CONVERSION_NON_VIDEO_FILE_ACTION }}"
      AUTOMATED_CONVERSION_OUTPUT_SUBDIR: "{{ handbrake_AUTOMATED_CONVERSION_OUTPUT_SUBDIR }}"
      AUTOMATED_CONVERSION_SOURCE_STABLE_TIME: "{{ handbrake_AUTOMATED_CONVERSION_SOURCE_STABLE_TIME }}"
      AUTOMATED_CONVERSION_CHECK_INTERVAL: "{{ handbrake_AUTOMATED_CONVERSION_CHECK_INTERVAL }}"
      APP_NICENESS: "{{ handbrake_APP_NICENESS }}"
      CLEAN_TMP_DIR: "{{ handbrake_CLEAN_TMP_DIR }}"
      UMASK: "{{ handbrake_converted_files_UMASK }}"
    restart_policy: unless-stopped
    labels:
      traefik.enable: "{{ handbrake_available_externally | string }}"
      traefik.http.routers.handbrake.rule: "Host(`handbrake.{{ ansible_nas_domain }}`)"
      traefik.http.routers.handbrake.tls.certresolver: "letsencrypt"
      traefik.http.routers.handbrake.tls.domains[0].main: "{{ ansible_nas_domain }}"
      traefik.http.routers.handbrake.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
      traefik.http.services.handbrake.loadbalancer.server.port: "5800"
    memory: "{{ handbrake_memory }}"
